Repository Omni-Libraries/omni-authify, pull requests merged in 2024-12, with the labels that each got.

#28 mukhsin
  docs/usage/django.md
  omni_authify/frameworks/django.py
  omni_authify/frameworks/drf.py
  omni_authify/providers/base.py
  omni_authify/providers/facebook.py
  omni_authify/providers/instagram.py
  setup.py
  tests/frameworks/test_flask.py
  tests/providers/apple/__init__.py
  tests/providers/apple/test_apple.py
  tests/providers/github/__init__.py
  tests/providers/github/test_github.py
  tests/providers/google/__init__.py
  tests/providers/google/test_google.py
  tests/providers/instagram/__init__.py
  tests/providers/instagram/test_instagram.py
  tests/providers/linkedin/__init__.py
  tests/providers/linkedin/test_linkedin.py
  tests/providers/telegram/__init__.py
  tests/providers/telegram/test_telegram.py
  tests/providers/twitter/__init__.py
  tests/providers/twitter/test_twitter.py
Labels: bug, documentation, enhancement, good first issue

#29 More robust version: 0.1.2
  docs/usage/django.md
  omni_authify/frameworks/django.py
  omni_authify/frameworks/drf.py
  omni_authify/providers/base.py
  omni_authify/providers/facebook.py
  omni_authify/providers/instagram.py
  setup.py
  tests/frameworks/test_flask.py
  tests/providers/apple/__init__.py
  tests/providers/apple/test_apple.py
  tests/providers/github/__init__.py
  tests/providers/github/test_github.py
  tests/providers/google/__init__.py
  tests/providers/google/test_google.py
  tests/providers/instagram/__init__.py
  tests/providers/instagram/test_instagram.py
  tests/providers/linkedin/__init__.py
  tests/providers/linkedin/test_linkedin.py
  tests/providers/telegram/__init__.py
  tests/providers/telegram/test_telegram.py
  tests/providers/twitter/__init__.py
  tests/providers/twitter/test_twitter.py
Labels: documentation, enhancement

#30 mukhsin
  omni_authify/__init__.py
  setup.py
Labels: bug

#37 mukhsin
  docs/usage/django-drf.md
  docs/usage/django.md
  docs/usage/fastapi.md
  omni_authify/core/utils.py
  omni_authify/frameworks/drf.py
  omni_authify/frameworks/fastapi.py
  omni_authify/providers/base.py
  requirements.txt
  setup.py
  tests/providers/facebook/test_facebook.py
Labels: bug, documentation, enhancement, good first issue

#41 Mukhsin - GitHub Oauth2 Implemented!
  docs/Setup/facebook.md
  docs/Setup/github.md
  docs/images/github/cridentials.png
  docs/images/github/final_result.png
  docs/images/github/new_auth_app.png
  docs/images/github/oauth_configs.png
  docs/usage/django-drf.md
  docs/usage/django.md
  docs/usage/fastapi.md
  omni_authify/__init__.py
  omni_authify/core/oauth.py
  omni_authify/core/utils.py
  omni_authify/frameworks/django.py
  omni_authify/frameworks/drf.py
  omni_authify/frameworks/fastapi.py
  omni_authify/providers/__init__.py
  omni_authify/providers/github.py
  omni_authify/settings.py
  tests/providers/github/test_github.py
Labels: documentation, enhancement

#42 Mukhsin -- GitHub Oauth2 Implemented Successfully!
  docs/Setup/facebook.md
  docs/Setup/github.md
  docs/Setup/linkedin.md
  docs/images/github/cridentials.png
  docs/images/github/final_result.png
  docs/images/github/new_auth_app.png
  docs/images/github/oauth_configs.png
  docs/usage/django-drf.md
  docs/usage/django.md
  docs/usage/fastapi.md
  omni_authify/__init__.py
  omni_authify/core/oauth.py
  omni_authify/core/utils.py
  omni_authify/frameworks/django.py
  omni_authify/frameworks/drf.py
  omni_authify/frameworks/fastapi.py
  omni_authify/providers/__init__.py
  omni_authify/providers/github.py
  omni_authify/settings.py
  setup.py
  tests/providers/github/test_github.py
Labels: documentation, enhancement

#46 Bumping version: 0.1.4 -> GitHub Oauth2
  omni_authify/__init__.py
  setup.py
Labels: documentation, enhancement

#48 mukhsin
  docs/index.md
Labels: documentation

#52 Muhammadali
  .gitignore
  docs/Setup/github.md
  docs/Setup/google.md
  docs/images/google/final_result1.jpg
  docs/images/google/final_result2.jpg
  docs/images/google/step-2/1.jpg
  docs/images/google/step-2/2.jpg
  docs/images/google/step-2/3.jpg
  docs/images/google/step-2/4.jpg
  docs/images/google/step-3/1.jpg
  docs/images/google/step-3/2.jpg
  docs/images/google/step-3/3.jpg
  docs/images/google/step-3/4.jpg
  docs/images/google/step-3/5.jpg
  docs/images/google/step-4/1.jpg
  docs/images/google/step-4/2.jpg
  docs/images/google/step-4/3.jpg
  docs/images/google/step-4/4.jpg
  docs/images/google/step-4/5.jpg
  docs/images/google/step-5/1.jpg
  docs/images/google/step-5/2.jpg
  docs/images/google/step-5/3.jpg
  docs/usage/django-drf.md
  docs/usage/django.md
  omni_authify/__init__.py
  omni_authify/core/oauth.py
  omni_authify/core/utils.py
  omni_authify/providers/__init__.py
  omni_authify/providers/google.py
  tests/providers/google/manual_test_google.py
  tests/providers/google/test_google.py
Labels: invalid

#62 Bumping version: 0.1.6
  .github/dependabot.yml
  .github/workflows/publish.yml
  .gitignore
  MANIFEST.in
  README.md
  docs/Setup/github.md
  docs/Setup/google.md
  docs/images/google/img.png
  docs/images/google/img_1.png
  docs/images/google/img_2.png
  docs/images/google/step-2/1.jpg
  docs/images/google/step-2/2.jpg
  docs/images/google/step-2/3.jpg
  docs/images/google/step-2/4.jpg
  docs/images/google/step-3/1.jpg
  docs/images/google/step-3/2.jpg
  docs/images/google/step-3/3.jpg
  docs/images/google/step-3/4.jpg
  docs/images/google/step-3/5.jpg
  docs/images/google/step-4/1.jpg
  docs/images/google/step-4/2.jpg
  docs/images/google/step-4/3.jpg
  docs/images/google/step-4/4.jpg
  docs/images/google/step-4/5.jpg
  docs/images/google/step-5/1.jpg
  docs/images/google/step-5/2.jpg
  docs/images/google/step-5/3.jpg
  docs/images/google/step-5/publish.png
  docs/usage/django-drf.md
  docs/usage/django.md
  docs/usage/fastapi.md
  omni_authify/__init__.py
  omni_authify/core/oauth.py
  omni_authify/core/utils.py
  omni_authify/frameworks/fastapi.py
  omni_authify/providers/__init__.py
  omni_authify/providers/base.py
  omni_authify/providers/google.py
  omni_authify/providers/instagram.py
  omni_authify/settings.py
  setup.py
  tests/providers/google/manual_test_google.py
  tests/providers/google/test_google.py
Labels: documentation, enhancement

#67 Release
  docs/Setup/facebook.md
  docs/Setup/google.md
  docs/Setup/linkedin.md
  docs/images/linkedin/consent.png
  docs/images/linkedin/login.png
  docs/images/linkedin/step-1/create_app.png
  docs/images/linkedin/step-1/create_company.png
  docs/images/linkedin/step-4/Screenshot 2024-12-20 at 01.45.49.png
  docs/images/linkedin/step-4/img.png
  docs/images/linkedin/step-4/scopes.png
  docs/images/linkedin/verify.png
  docs/installation.md
  docs/usage/django-drf.md
  docs/usage/django.md
  docs/usage/fastapi.md
  omni_authify/__init__.py
  omni_authify/core/oauth.py
  omni_authify/core/utils.py
  omni_authify/providers/__init__.py
  omni_authify/providers/facebook.py
  omni_authify/providers/google.py
  omni_authify/providers/linkedin.py
  omni_authify/settings.py
  setup.py
  tests/providers/linkedin/test_linkedin.py
Labels: documentation, enhancement

#73 Mukhsin
  docs/Setup/linkedin.md
  docs/images/linkedin/step-4/display_scopes.png
Labels: documentation, enhancement
